@echo off
echo Starting Real Estate Web Application with Map Search Features...

echo Starting backend server...
start cmd /k "cd . && npm run server"

echo Starting frontend development server...
start cmd /k "cd frontend && npm start"

echo Servers are starting. Please wait...
echo Backend will be available at http://localhost:9000/
echo Frontend will be available at http://localhost:3000/

echo Press any key to close all servers when done...
pause

echo Shutting down servers...
taskkill /f /im node.exe 